/**:
  ros__parameters:
    controllers:
      type: "mellinger_mavlink"
      update_rate_hz: 100.0
      mellingercontroller:
        mass: 3.5
        gains:
          kp: [2.5, 2.5, 8.0]
          kd: [5.2, 5.2, 5.8]
          kr: [5.0, 5.0, 4.2]
    mavlink:
      discovery_timeout_s: 30.0
      telemetry_rate_hz: 100.0
      telemetry_timeout_s: 0.5
