/**:
  ros__parameters:
    subscribers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        follow: "fmu/mode/follow"
      state:
        state: "fmu/telemetry/state"
    publishers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        offboard: "fmu/in/offboard_control_mode"
        request: "fmu/in/vehicle_command"
    controllers:
      type: "los4"
      loscontroller:
        gains:
          k1: 1.0
          k2: 20.0
        publishers:
          lateral: "fmu/in/fixed_wing_lateral_setpoint"
          longitudinal: "fmu/in/fixed_wing_longitudinal_setpoint"
      los2controller:
        gains:
          k1: 1.0
          k2: 10.0
        publishers:
          lateral: "fmu/in/fixed_wing_lateral_setpoint"
          longitudinal: "fmu/in/fixed_wing_longitudinal_setpoint"
      los3controller:
        m: 1.5  # kg
        Tmax: 120.0  # N
        gains:
          k1: 1.0
          k2: 20.0
          kpE: 0.05
          kiE: 0.005
          kpB: 0.002
          kiB: 0.00001
          ka: 6.0
        limits:
          throttle_min: 0.0
          throttle_max: 1.0
          pitch_min: -0.52
          pitch_max: 0.52
          lateral_acceleration_min: -6.0
          lateral_acceleration_max: 6.0
        publishers:
          lateral: "fmu/in/fixed_wing_lateral_setpoint"
          longitudinal: "fmu/in/fixed_wing_longitudinal_setpoint"
      los4controller:
        m: 1.5  # kg
        Tmax: 120.0  # N
        gains:
          k1: 1.0
          k2: 18.0
          kpE: 0.05
          kiE: 0.005
          kpB: 0.002
          kiB: 0.00001
          ka: 6.0
          kphi: 10.0
          ktheta: 10.0
        limits:
          throttle_min: 0.0
          throttle_max: 1.0
          pitch_min: -0.52
          pitch_max: 0.52
          lateral_acceleration_min: -6.0
          lateral_acceleration_max: 6.0
        publishers:
          setpoint: "fmu/in/vehicle_rates_setpoint"
