/**:
  ros__parameters:
    subscribers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        follow: "fmu/mode/follow"
      state:
        state: "fmu/telemetry/state"
    publishers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        offboard: "fmu/in/offboard_control_mode"
        request: "fmu/in/vehicle_command"
    controllers:
      type: "combined_direct"
      onboardcontroller:
        publishers:
          setpoint: "fmu/in/trajectory_setpoint"
      mellingercontroller:
        mass: 3.5 # Kg
        gains:
          kp: [2.5, 2.5, 8.0]
          kd: [5.2, 5.2, 5.8]
          kr: [5.0, 5.0, 4.2]
        publishers:
          setpoint: "fmu/in/vehicle_rates_setpoint"
      combineddirectcontroller:
        fixed_wing_namespace: "drone2"
        fixed_wing_vehicle_id: 2
        publish_rate_hz: 50.0
        damping: 0.01
        limits:
          motor_min: -1.0
          motor_max: 1.0
          servo_min: -1.0
          servo_max: 1.0
        max_thrust:
          quad: 33.51
          fixed_wing: 104.72
        subscribers:
          wrench: "fmu/in/combined_wrench"
        publishers:
          shuttle_motors: "fmu/in/actuator_motors"
