/**:
  ros__parameters:
    subscribers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        follow: "fmu/mode/follow"
      state:
        state: "fmu/telemetry/state"
    publishers:
      mode:
        arm: "fmu/mode/arm"
        disarm: "fmu/mode/disarm"
        takeoff: "fmu/mode/takeoff"
        orbit: "fmu/mode/orbit"
        land: "fmu/mode/land"
        kill: "fmu/mode/kill"
        offboard: "fmu/in/offboard_control_mode"
        request: "fmu/in/vehicle_command"
    controllers:
      type: "mellinger"
      onboardcontroller:
        publishers:
          setpoint: "fmu/in/trajectory_setpoint"
      mellingercontroller:
        mass: 2.0 # Kg
        gains:
          kp: [5.0, 5.0, 8.0]
          kd: [4.2, 4.2, 4.8]
          kr: [5.0, 5.0, 5.0]
        publishers:
          setpoint: "fmu/in/vehicle_rates_setpoint"


